-- Rename the three contact-log axes from Spanish to English: `entrega` -> `delivery`,
-- `camino` -> `path`, `resultado` -> `outcome`. Field/type names only — enum VALUES are
-- unchanged (DISPATCHED, ENGAGED, PAYMENT_PROMISE, etc. all stay exactly as they are).
--
-- Hand-written rather than `prisma migrate dev`-generated: Prisma has no way to express "this
-- column/type kept its data, only its name changed" from a schema diff alone, so its
-- autogenerated SQL for a rename is a DROP + CREATE, which would silently destroy every
-- existing gestión's axes. RENAME COLUMN / RENAME TYPE preserve the data and are the only
-- safe way to do this.

ALTER TABLE "account_contact_logs" RENAME COLUMN "entrega" TO "delivery";
ALTER TABLE "account_contact_logs" RENAME COLUMN "camino" TO "path";
ALTER TABLE "account_contact_logs" RENAME COLUMN "resultado" TO "outcome";

ALTER TYPE "Entrega" RENAME TO "Delivery";
ALTER TYPE "Camino" RENAME TO "Path";
ALTER TYPE "Resultado" RENAME TO "Outcome";

-- Keep index names in sync with Prisma's default naming convention (table_field(s)_idx), so a
-- future `prisma migrate diff` against this schema reports no drift.
ALTER INDEX "account_contact_logs_entrega_idx" RENAME TO "account_contact_logs_delivery_idx";
ALTER INDEX "account_contact_logs_resultado_idx" RENAME TO "account_contact_logs_outcome_idx";
ALTER INDEX "account_contact_logs_entrega_agentType_contactedAt_idx"
  RENAME TO "account_contact_logs_delivery_agentType_contactedAt_idx";

-- The two CHECK constraints added by the original axes migration were already named after
-- the English concept (`..._delivery_reason_check`, `..._one_way_channel_check`), not the
-- Spanish column, so they need no rename.
