-- Activate Fonoster answering-machine detection (AMD, PR #893) in QCobro.
--
-- Renames the reserved `Path` enum value `VOICEMAIL` to `ANSWERED_BY_MACHINE`. Fonoster's
-- detector can only ever report HUMAN/MACHINE/UNKNOWN (it never distinguishes a voicemail
-- greeting from an IVR menu), so QCobro collapses both into one value. Hand-written rather
-- than `prisma migrate dev`-generated: Prisma has no way to express an enum VALUE rename from
-- a schema diff alone (its autogenerated SQL would drop and recreate the type), which would
-- destroy any existing row using the old value. `RENAME VALUE` preserves data. As of this
-- migration, nothing in the codebase writes `VOICEMAIL` (confirmed by grep across `mods/`),
-- so this is expected to affect zero live rows.
ALTER TYPE "Path" RENAME VALUE 'VOICEMAIL' TO 'ANSWERED_BY_MACHINE';

-- Per-template opt-out from the new hang-up-on-machine behavior (default on). Additive and
-- non-breaking: every existing template backfills to true, matching the product decision
-- that pre-recorded campaigns should hang up on a detected machine without requiring every
-- template to be edited first.
ALTER TABLE "voice_prerecorded_configs" ADD COLUMN "hangupOnMachineDetected" BOOLEAN NOT NULL DEFAULT true;
